From ubuntu:precise
MAINTAINER Bastien Jaillot <bjaillot@jolicode.com>

RUN apt-get update && apt-get install -y python-software-properties
RUN add-apt-repository ppa:ondrej/php5-oldstable && apt-get update

RUN apt-get install -y php5-cli
